[server]
# Enable static file serving for CSS
enableStaticServing = true

[theme]
# Optional: Set default theme parameters
primaryColor = "#2e3192"
backgroundColor = "#1b1b1b"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#ffffff"
font = "sans serif"

[custom]
# Document your CSS file (purely informational)
cssFile = "styles.css"
cssDescription = "Custom dashboard styling with animated gradients and dark theme"
cssVersion = "1.0"
